name: CI
on: [push]
jobs:
  ci-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: pushd /tmp && git clone --depth 1 https://github.com/awslabs/git-secrets.git && cd ./git-secrets && PREFIX=/tmp/git-secrets make install && popd
      - run: npm install -g typescript
      - run: npm install -g yarn
      - run: npm install -g oss-attribution-generator
      - run: PATH=/tmp/git-secrets/bin:$PATH bash ./scripts/build.sh