name: CI
on: [push, pull_request]
jobs:
  ci-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: pushd /tmp && git clone --depth 1 https://github.com/awslabs/git-secrets.git && cd ./git-secrets && PREFIX=/tmp/git-secrets make install && popd
      - run: npm install -g typescript
      - run: npm install -g yarn
      - run: npm install -g oss-attribution-generator
      - run: PATH=/tmp/git-secrets/bin:$PATH bash ./scripts/build.sh